dateModified: 1583493724
email:
  fromEmail: clarapasteau@gmail.com
  fromName: valentine
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  9927952a-8ccc-4948-a0a5-c7b440f2d673:
    name: Common
routes:
  2d7aca0e-78db-4400-9a41-37f46a831283:
    siteUid: null
    sortOrder: 1
    template: /_article
    uriParts:
      - 'article/{slug}'
    uriPattern: 'article/{slug}'
siteGroups:
  df19bf3e-cc75-4c19-821d-81cbd484c4ed:
    name: valentine
sites:
  e92180d7-4855-404c-b2fb-69cbeb45e447:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: valentine
    primary: true
    siteGroup: df19bf3e-cc75-4c19-821d-81cbd484c4ed
    sortOrder: 1
system:
  edition: solo
  live: true
  name: valentine
  schemaVersion: 3.4.10
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
